title: pac4cli
email: devteam@pac4cli.io
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pac4cli.io" # the base hostname & protocol for your site
twitter_username: timo_kluck
github_username:  tkluck

# Build settings
markdown: kramdown

theme: jekyll-theme-slate