[package]
name = "pac4cli"
version = "0.1.0"
authors = ["Timo Kluck <tkluck@infty.nl>"]

[dependencies]
tokio = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
libc = "0.2.0"
argparse = "0.2.1"
futures = "0.1.17"
uri = "0.3.0"
dbus = "0.6.1"
dbus-tokio = "0.2.1"
hyper = "0.11"
slog = "2.2.3"
slog-scope = "4.0.1"
slog-term = "2.3.0"
tokio-signal = "0.1.5"
